sources:
  - name: Countries
    handler:
      graphql:
        endpoint: https://countries.trevorblades.com/
    transforms:
      - prefix:
          value: CTRY_
          includeRootOperations: true
  - name: CartQL
    handler:
      graphql:
        endpoint: https://api.cartql.com
    transforms:
      - prefix:
          value: CQL_
          includeRootOperations: true
  - name: Stripe
    handler:
      openapi:
        source: https://raw.githubusercontent.com/stripe/openapi/refs/heads/master/openapi/spec3.json
        baseUrl: https://api.stripe.com
        operationHeaders:
          Authorization: Bearer ${STRIPE_SECRET_KEY}